#!/bin/bash

# Configures the environment for TopOSM rendering.
# Change these settings to match your setup.

# Postgres settings
export DB_HOST="localhost"
export DB_NAME="osm"
export DB_PORT=5432 # local postgres port
export DB_PREFIX="planet_osm" # prefix for all tables
export DB_USER="mapnik" # username
export DB_PASS="mapnik"
export CONTOURS_DB="ned"
export CONTOURS_TABLE="contours"
export NHD_DB="nhd"
export NHD_TABLE_PREFIX=""

# Data directories
export WORLD_BOUNDARIES_DIR="/home/mapnik/world_boundaries"
export NHD_DIR="/srv/usgs/NHD" # NHD shapefiles
export NLCD_DIR="/srv/usgs/NLCD"
export NED13_DIR="/srv/usgs/NED/13" # NED 1/3" GeoTIFFs
export HILLSHADE_DIR="/srv/usgs/NED/hillshade" # Hillshade GeoTIFFs
export COLORMAP_DIR="/srv/usgs/NED/colormap" # Colormap GeoTIFFs
export HYPSORELIEF_DIR="/srv/usgs/NED/hypsorelief" # Hillshade with hypsometric tinting
export SHIELDS_DIR="/srv/shields" # generated route shield images

# Output directories
export BASE_TILE_DIR="/srv/tiles" # output directory
export TEMP_DIR="/srv/usgs/cache" # preprocessed data and temporary files

# Misc files
export OSM2PGSQL_STYLE_FILE="/home/mapnik/default.style"
export COLORFILE="$HOME/src/toposm-new/colors.txt" # elevation-to-color mapping

# Extra TrueType fonts directory (for Mapnik)
export EXTRA_FONTS_DIR="/usr/share/fonts/truetype"

# Render settings
# NOTE: Apparently the Cairo backend is not thread safe (because,
# it turns out, cairo/pixman is not, so let's leave this at 1 for now...
export RENDER_THREADS=1 # typically equal to # of cores
export TILE_SIZE=256
export BORDER_WIDTH=128
export ERROR_LOG="errors.log"
export CACHE_LAYERS="contours"

# Quality setting for combined JPEG layer
export JPEG_QUALITY=90

# The area we're interested in
# (this setting limits both import and rendering)
# E.g. Conterminous US: "-127,23,-65,51"

export XMINLL=-127
export XMAXLL=-65
export YMINLL=23
export YMAXLL=51

export EXTENTS_LATLON="$XMINLL,$YMINLL,$XMAXLL,$YMAXLL"
export EXTENTS_MERCATOR="-20037508,-19929239,20037508,19929239"

# Enable/disable extra debug/diagnostic messages during rendering
export TOPOSM_DEBUG=1

# Used to check that the env is set. Don't modify.
export TOPOSM_ENV_SET=1

# Use a local, patched mapnik2:
#LOCAL_MAPNIK_PREFIX="$HOME"
#export LD_LIBRARY_PATH="$LOCAL_MAPNIK_PREFIX/lib"
#export PYTHONPATH="$LOCAL_MAPNIK_PREFIX/lib/python2.7/site-packages"

